<Project Sdk="Aspire.AppHost.Sdk/13.1.2">

  <ItemGroup>
    <ProjectReference Include="..\MSDocsAIBot\MSDocsAIBot.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>23865cbe-018c-4b39-a5fd-683e070c76d2</UserSecretsId>
  </PropertyGroup>

</Project>
